function exportResultsToExcel(pipeTable, nodeTable, fileName)

    writetable( ...
        pipeTable, ...
        fileName, ...
        'Sheet', 'Pipe_Optimization');

    writetable( ...
        nodeTable, ...
        fileName, ...
        'Sheet', 'Hydraulic_Nodes');

end