function exportResultsToExcel(pipeTable, nodeTable, benchmarkTable, fileName)

    writetable( ...
        pipeTable, ...
        fileName, ...
        'Sheet', 'Pipe_Optimization');

    writetable( ...
        nodeTable, ...
        fileName, ...
        'Sheet', 'Hydraulic_Nodes');

    if ~isempty(benchmarkTable)
        writetable( ...
            benchmarkTable, ...
            fileName, ...
            'Sheet', 'Algorithm_Benchmark');
    end

end