function tempInpPath = createTempInpFile(inpFilePath)

    tempInpPath = [tempname '.inp'];

    [success, message, ~] = copyfile( ...
        inpFilePath, ...
        tempInpPath, ...
        'f');

    if ~success
        error( ...
            'WDSOptimizer:TempFileCreationFailed', ...
            'Failed to create temporary INP file: %s', ...
            message);
    end

end